### ISSUE TITLE
Corrupt file: Binary v2.2 for windows 64 bit

### ISSUE THREAD

**Issue by lw3eov** [openwall/johnny#122]
Hi,

What is the exact size in bytes of the compressed .zip binary v2.2 for windows 64 bit? The one I downloaded is showing as corrupted by winrar 5.71 (for windows 64 bit). Please also tell me what is the size of the uncompressed executable installation .exe file.

I downloaded it twice and I am getting the same error! I use winrar a lot and I don't normally get this errors.

This is the place where I am downloading the file from:

https://openwall.info/wiki/john/johnny#Binary-redistributables

Thanks
Regards

Marcelo

**Comment by shinnok** [comment]
Hi @lw3eov,

Here's the sha for v2.2 files:
```
$unzip -vvv johnny_2.2_win.zip
Archive:  johnny_2.2_win.zip
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
28632019  Defl:N 20750621  28% 08-24-2015 11:09 eff10632  johnnyInstaller.exe
--------          -------  ---                            -------
28632019         20750621  28%                            1 file
$shasum johnny*
4797f346873050b432ea716a158fa867ccc9a281  johnnyInstaller.exe
5ae315a5ca0e15245890b97a2cb15b41bd16fd78  johnny_2.2_win.zip
```

**Comment by solardiz** [comment]
I've just downloaded the archive from @lw3eov's wiki link above, and it matches SHA-1's in @shinnok's comment. So I assume the issue, if any, was limited to @lw3eov's downloads back then?

Adding to the info posted by @shinnok, the full `johnny_2.2_win.zip` file is 20750757 bytes (the `unzip` output above didn't show that - it shows only per-file compressed sizes, not including the archive file header size). And its SHA-256 is: `c588b56648c375a3d820a22b6aeec094fb90b399287f1a8cf31a9d42b0149287`
